import { IProduct, SwordEdge } from "../../mongoose/models/Product";
import mongoose from "mongoose";
import { MetalType, SwordType } from "../../mongoose/models/Product";

const products: IProduct[] = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Acre Broadsword",
    image: "/assets/products/broadsword/Acre-Broadsword.png",
    price: 40.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.BROADSWORD,
    description: [
      "This medieval Acre Crusader Broadsword from Windlass Steelcrafts Battlecry collection is a formidable weapon of proven worth. This classic knightly sword was ideal for sword and shield or sword and buckler combat, whether on foot or horseback. The Acre crusader sword is a stout and fearsome blade that takes advantage of its heft, width, center, and gravity to deliver deadly slashing cuts, and hacking blows and thrusts.",

      "One can easily imagine how this weapon shredded both mail and leather armors across Europe and Asia-minor for centuries. With a wide cross-guard of over 8', it's no sword for the softhearted or weak-spirited. Its practical cruciform hilt with single-hand grip and disc pommel was to be the functional model for countless other sword styles to follow. To know why and how the Medieval warrior became so successful you could do no better than starting with this blade.",

      "Includes a matching scabbard with belt stop, and certificate of authenticity signed by each smith that touched your blade through every step of the forging process.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1060,
    total_length: 39.25,
    blade_length: 32.75,
    blade_width: 2,
    sword_weight: 3,
    point_of_balance: 6,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Final Fantasy Broadsword",
    image: "/assets/products/broadsword/Final-Fantasy-Broadsword.webp",
    price: 199.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.BROADSWORD,
    description: [
      "Broadsword (ブロードソード, Borōdosōdo?), also known as Shortsword and Broad, is a common recurring weapon in the series. It is often the weakest, or one of the weakest, swords in the game, and is usually wielded by heavy melee classes such as Knights. It does not grant any special abilities, and is relatively weak after the opening area.",
    ],
    metal_type: MetalType.SPRING_STEEL,
    total_length: 40,
    blade_length: 32.5,
    blade_width: 1.25,
    sword_weight: 2,
    point_of_balance: 5,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Imperial Knights Broadsword",
    image: "/assets/products/broadsword/Imperial-Knights-Broadsword.png",
    price: 399.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.BROADSWORD,
    description: [
      "Fight like some of the fiercest warriors this world has ever seen when using our handmade Imperial Knights Broadsword. Crafted from steel with an eye for authenticity, this sword is the perfect weapon for a variety of swordsmen. This functional sword has a fuller running the length of the blade for increased balance and stability. A cruciform hilt and wheel pommel round out the wire corded handle making this a uniquely inspired broadsword for the modern day. Included with the blade is a solid wood scabbard wrapped in black leather providing you with everything you need to wield this bold blade. A great one-handed sword, this blade can handle a variety of scenarios with its hardened and tempered steel making it ideal as your primary weapon for combat and costume scenarios.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 39.5,
    blade_length: 29.25,
    blade_width: 7.25,
    sword_weight: 4,
    point_of_balance: 7,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Romanian Broadsword",
    image: "/assets/products/broadsword/Romanian-Broadsword.png",
    price: 399.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.BROADSWORD,
    description: [
      "Broadsword The Broadsword scales primarily with Strength and Dexterity and is a good Weapon for melee ranged combat and dealing slashing attacks to enemies. ",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 34,
    blade_length: 25,
    blade_width: 8,
    sword_weight: 3,
    point_of_balance: 6,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Training Broadsword",
    image: "/assets/products/broadsword/Training-Broadsword.png",
    price: 499.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.BROADSWORD,
    description: [
      "Martial Artists have known a simple truth for ages – If your ultimate goal is to wield a sharp blade safely and effectively, you need to supplement your training with a tool that approximates the size, feel and heft of a blade, yet minimizes the possibility of causing grievous, permanent injury to yourself or your training partner. This concept was implemented by many cultures, including the ancient Romans, who used wooden swords to train their Gladiators. Cold Steel’s solution to these dilemmas was to design a line of synthetic polymer substitutes.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 34,
    blade_length: 25,
    blade_width: 8,
    sword_weight: 2,
    point_of_balance: 5,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Wooden Pirate Cutlass",
    image: "/assets/products/cutlass/Black-Wooden-Pirate-Cutlass.png",
    price: 50.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.CUTLASS,
    description: [
      "The Black Wooden Pirate Cutlass features a broad single edged blade with a fuller along the spine and a curve near the tip. This wooden sword is an excellent choice for sparring and adds a great touch to any privateer costume. The D guard protects your hand from incoming blows. The grip is embellished with narrow carved lines. Perfect for cosplay ensembles, combat training, and theatrical productions, the Black Wooden Pirate Cutlass is great for all ages.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 30,
    blade_length: 20,
    blade_width: 4,
    sword_weight: 2,
    point_of_balance: 5,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Earth Cutlass",
    image: "/assets/products/cutlass/Earth-Cutlass.png",
    price: 109.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.CUTLASS,
    description: [
      "The blade of this sword is inlaid with amber. Its small size makes it both easy to handle and invaluable when fighting in close quarters.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1060,
    total_length: 32,
    blade_length: 24.25,
    blade_width: 5,
    sword_weight: 5,
    point_of_balance: 7,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Fantasy Cutlass",
    image: "/assets/products/cutlass/Fantasy-Cutlass.webp",
    price: 159.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.CUTLASS,
    description: [
      "Fantasy cutlass with scabbard.This pirate sword is perfect for a swash buckling pirate!",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 30.5,
    blade_length: 25.5,
    blade_width: 1.25,
    sword_weight: 1,
    point_of_balance: 4,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "LARP Corsair Cutlass",
    image: "/assets/products/cutlass/LARP-Corsair-Cutlass.png",
    price: 395.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.CUTLASS,
    description: [
      "Crafted from durable closed cell foam, the LARP Corsair Cutlass follows a design perfect for both high fantasy and historical roles. Become a swashbuckling buccaneer from the golden age of piracy with this sword at your side. Possessing a curved scimitar blade, this LARP weapon is best suited for chopping and piercing through the flesh of your foes. A single quillon forms form the basket of the hilt. Wrapping made from split-leather strengthens the grip.",
      "This LARP weapon is made from an extremely durable foam that does not shred and sealed with a strong coating of latex. Safety is always a concern in LARP, which is why this weapon has a round, flexible fiberglass core with strong Kevlar core tip protection.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1075,
    total_length: 37.5,
    blade_length: 27,
    blade_width: 3,
    sword_weight: 1,
    point_of_balance: 5,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Samurai Sword Cutlass",
    image: "/assets/products/cutlass/Samurai-Swords-Cutlass.png",
    price: 599.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.CUTLASS,
    description: [
      "Before the seven seals are torn away… CAS proudly introduces the A.P.O.C. Swords from Dragon King. Whether it be plague, natural disaster, mass hysteria, nuclear fallout, zombies, alien invasion or mankind’s inevitable A.I. war, these tactical swords feature a meek and functional design against unremitting maintenance and corrosion in those bleak future days. But such thought in design are expected from combining the expertise of the artisans of Dragon King and the mind of sword maker, Gus Trim. Tactically black and no frills, the removable durable black G10 handle scales cover a thick full-tang on the Black Oxide coated 9260 Spring Steel blades.",
      "The black textured fiberglass sheaths are fitted to a Molle compatible kydex platform that allows you to secure your swords to belt or pack in multiple carry positions. For belt or sling carry setups the platform has four slots 1 3/8″ long and 1/8″ wide. A notch in the handle and the platform allows for stealth unsheathing as well as locking the sword securely for inverted maneuvers. No preparations for the end times are complete without an A.P.O.C. tactical sword for when the bullets run out, the knives are too short and your life is on the line.",
    ],
    metal_type: MetalType.SPRING_STEEL,
    total_length: 29.75,
    blade_length: 21.5,
    blade_width: 8,
    sword_weight: 5,
    point_of_balance: 3,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Flower Katana",
    image: "/assets/products/katana/Black-Flower-Katana.png",
    price: 999.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KATANA,
    description: [
      "Katana are known not only for their fast and deadly power, but their beauty as well, as the swords of samurai showed their nobility and wealth. The Black Flower Katana is inspired by Japanese sword styles and has a flower petal guard made of black metal and accented with just a touch of gold color. The round, cut-out tsuba is at the base of a brass blade collar, followed by a white faux rayskin handle and antique gold tone menuki palm ornamentation. Black cord wraps over the entire handle. The curved blade is made of carbon steel and has the distinctive slender shape and slight curve of historical Japanese katana, as well as a fuller along most of its length. Keep the blade safe with the included matching scabbard. A black cloth cover is also included for further protection. This decorative samurai sword is a remarkable addition to any sword collection, and adds the style of a Japanese warrior from the feudal era into any decor or display.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1060,
    total_length: 41.25,
    blade_length: 28.25,
    blade_width: 4,
    sword_weight: 3,
    point_of_balance: 4,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Katana",
    image: "/assets/products/katana/Black-Katana.png",
    price: 552.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KATANA,
    description: [
      "Fully handmade sword, highly polished blade, impressively sized yet easy to wield and deft in battle",
      " 1045 carbon steel, 28 inches blade, blade carving, battle ready, brown cord handle, alloy tsuba, alloy fittings, piano paint scabbard, sharpened, katana, full tang, handmade, blade polished, 40.5 inches, hardwood scabbard",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 40.5,
    blade_length: 28,
    blade_width: 4,
    sword_weight: 3,
    point_of_balance: 5,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Final Fantasy Mako Katana",
    image: "/assets/products/katana/Final-Fantasy-Mako-Katana.webp",
    price: 385.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KATANA,
    description: [
      "The Mako Katana is one of Sephiroth's unlockable weapons. It can be obtained either by random chance when redeeming a Treasure token, or by purchasing them from the Shop for 7,200 Gil. Like all other characters' weapons, having it equipped carries no advantages or disadvantages.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1060,
    total_length: 35,
    blade_length: 25,
    blade_width: 4,
    sword_weight: 5,
    point_of_balance: 4,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Green Katana",
    image: "/assets/products/katana/Green-Katana.png",
    price: 1023.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KATANA,
    description: [
      "Katana, full tang, handmade, 1045 carbon steel, battle ready, sharpened, blade polished, alloy fittings, green cord handle, 28 inches blade, 40.5 inches, gold blade",
      "Exclusive process yields stunning gold blade color, hand sharpened, full tang, battle ready sword",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 40.5,
    blade_length: 27.5,
    blade_width: 1.5,
    sword_weight: 3.5,
    point_of_balance: 3,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "LARP Dai Katana",
    image: "/assets/products/katana/LARP-Dai-Katana.png",
    price: 588.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KATANA,
    description: [
      "Anxious cries from the village captures the attention of a wandering samurai. Without hesitation, the Japanese warrior unleashes revenge upon the bandits. The LARP Dai Katana handles smoothly in the masterful grasp of the ronin. Be impressed by the graceful beauty of this Japanese sword. Made from durable close-celled foam, this katana possesses a strong, yet flexible fiberglass core. Carefully hand painted for stunning detail, gold and silver accents define the tsuba and tsuka. A beautiful black wrapping adorns the hilt, ending with a silver and gold kashira. Let this Japanese sword fulfill a noble purpose in service to the timeless samurai who ventures into the LARP realm.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 39.5,
    blade_length: 27.5,
    blade_width: 2,
    sword_weight: 4,
    point_of_balance: 3,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Random Katana",
    image: "/assets/products/katana/random-Katana.png",
    price: 329.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KATANA,
    description: [
      "A katana (刀, かたな) is a Japanese sword characterized by a curved, single-edged blade with a circular or squared guard and long grip to accommodate two hands. Developed later than the tachi, it was used by samurai in feudal Japan and worn with the edge facing upward. Since the Muromachi period, many old tachi were cut from the root and shortened, and the blade at the root was crushed and converted into katana.[4] The official term for katana in Japan is uchigatana (打刀) and the term katana (刀) often refers to single-edged swords from around the world.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1075,
    total_length: 40,
    blade_length: 25,
    blade_width: 5,
    sword_weight: 5,
    point_of_balance: 5,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Red Katana",
    image: "/assets/products/katana/Red-Katana.png",
    price: 884.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KATANA,
    description: [
      "Unique and striking blue steel blade, full-tang battle ready japanese katana samurai sword.",
      "Katana, red katana, purple blade, 1095 carbon steel, handmade, full tang, battle ready, sharpened, red scabbard, red cord handle, 40.5 inches, alloy fittings",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1095,
    total_length: 40.5,
    blade_length: 28.5,
    blade_width: 2,
    sword_weight: 2,
    point_of_balance: 4,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Hunting Knife",
    image: "/assets/products/knifes/Hunting-Knife.png",
    price: 583.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KNIFE,
    description: [
      "The Intrepid from Anglo Arms is indeed heavy duty, the knife is full tang, constructed from one single piece of very thick steel with no weak joints. Chunky, solid, heavy are the words that come to mind holding this great hunting knife.",
      "The handle is an ergonomic micarta overlay with a finger guard. The blade is extra wide and the weight of this results in effortless chopping cuts on branches. The blade measures 8 inches with a near 4 inch saw back.",
      "This exceptional knife comes with a very high quality nylon sheath with a belt loop, leg tie and a small front pouch ideal for a sharpening stone (stone not included).",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 13.5,
    blade_length: 8,
    blade_width: 2,
    sword_weight: 1,
    point_of_balance: 2,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Huntn Fisch Fixed Blade Knife",
    image: "/assets/products/knifes/Huntn-Fisch-Fixed-Blade-Knife.webp",
    price: 329.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KNIFE,
    description: [
      "This Larry Fischer-designed fixed blade hunting knife has multiple friction grooves along the spine for optimum blade control and a stylish, multi-colored G10 handle, with exceptional fit and finish. Together they serve one purpose: to get every ounce of dinner off your game. With the included high-quality sheath, you’ll be ready for deer that aren’t expecting you.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1060,
    total_length: 7.25,
    blade_length: 3,
    blade_width: 0.25,
    sword_weight: 1.25,
    point_of_balance: 1,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Outdoor Edge Wild Knife",
    image: "/assets/products/knifes/Outdoor-Edge-Wild-Knife.webp",
    price: 853.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KNIFE,
    description: [
      "Lightweight, 6-piece field-to-freezer game processing set complete with a full-tang caping knife, gut-hook skinner, boning knife, two-stage fine ceramic/coarse carbide sharpener, game cleaning gloves and hard-side carry case. Blades are hand finished shaving-sharp to ensure superior edge retention and performance. Non-slip rubberized blaze-orange handles never get lost and feature an embossed elk horn design for enhanced grip.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1075,
    total_length: 4,
    blade_length: 2.5,
    blade_width: 1,
    sword_weight: 1,
    point_of_balance: 2,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Pocket Knife Iowa Daryl's Gun Shop Knife",
    image:
      "/assets/products/knifes/Pocket-Knife-Iowa-Daryl's-Gun-Shop-Knife.png",
    price: 103.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KNIFE,
    description: [
      "Our lightest, most compact knife set with hard-side carry case is perfect for field use and home processing. Weighing just 20 ounces, this complete 6-piece set includes a full-tang caping knife, gut-hook skinner, boning/fillet knife, game cleaning gloves and two-stage ceramic/carbide sharpener to maintain a razor edge at all times. The 420J2 stainless steel blades are precisely heat treated and hand finished shaving-sharp. Rubberized, blaze-orange TPR handles offer high visibility in the field and ensure a non-slip grip, even when wet. Additionally, the elk horn inlay provides extra indexing points for greater control, and prevent fatigue during long use. Ensure the quality of the meat for your family and save the cost of commercial processing with the WildLite.",
    ],
    metal_type: MetalType.SPRING_STEEL,
    total_length: 8,
    blade_length: 2.5,
    blade_width: 2,
    sword_weight: 1,
    point_of_balance: 1,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Pocket Knife Le Thiers Knife",
    image: "/assets/products/knifes/Pocket-Knife-Le-Thiers-Knife.jpg",
    price: 238.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.KNIFE,
    description: [
      "Le Thiers Pocket knives by Fontenille Pataud bears the name of the city of Thiers, the French capital of cutlery. Coming from the reflection of a whole profession, it is subject to the respect of a charter (juranda) which implies the respect of strict specifications. Unlike Laguiole knives, the 'Le Thiers' name and patented design are strictly protected by the city of Thiers and the French government. The 'Le Thiers' series of pocket knives all feature an easy opening and locking blade system making it safer to use. The flexibility of the precision mechanism makes the knives easy to open and close. As with all Fontenille Pataud pocket knives, the cutting edge of the blades is protected by a solidly fixed blade stop.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1060,
    total_length: 10,
    blade_length: 5,
    blade_width: 1,
    sword_weight: 2,
    point_of_balance: 2,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Medieval Longsword",
    image: "/assets/products/long_sword/Medieval-Longsword.png",
    price: 534.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.LONGSWORD,
    description: [
      "This Medieval Longsword has a blade forged from high carbon steel; the crossguard and pommel are steel and the wooden grip is tightly bound in leather and finished with twisted steel wire inlay.",
      "The wood-core scabbard is overlaid in brown leather and finished with a protective steel chape and locket.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1095,
    total_length: 46.5,
    blade_length: 36.5,
    blade_width: 2,
    sword_weight: 3,
    point_of_balance: 6,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Phantom Forces Longsword",
    image: "/assets/products/long_sword/Phantom-Forces-Longsword.webp",
    price: 384.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.LONGSWORD,
    description: [
      "The Longsword featured in Phantom Forces is a traditional hand-and-a-half or' bastard' sword. Its closest Oakeshott blade classification is Type XIIa. The sword features an upwards-curving crossguard, with a cylindrical pommel (closest to type J1 of the Oakeshott pommel classification). The blade has a hexagonal profile. A cursive G is engraved into the écusson",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1095,
    total_length: 45,
    blade_length: 37,
    blade_width: 5,
    sword_weight: 4,
    point_of_balance: 5,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Robbert Stark Longsword",
    image: "/assets/products/long_sword/Robbert-Stark-Longsword.png",
    price: 853.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.LONGSWORD,
    description: [
      "Training with wooden swords is very practical, but when facing a real threat, survival is less than assured without a sturdy steel blade. But to be able to hold to this weapon, one needs to have gone through the adulthood rite of passage.",
      "After the series of trials, that are kept secret until I am facing them, I will officially be considered an adult. This means I will receive, like every man and woman of my clan, a sword. I will then be able to take part in the battles they fight, and help them defend what is ours.",
      "The Robbert Stark LARP sword is a great addition to the Squire collection. Made of safe Calimacil foam, this weapon will give you years of good use thanks to its unrivaled durability. The guard of the sword is steel-coloured and the handle is black. The blade is silver-coloured to give a unique and incredibly realistic look. ",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1075,
    total_length: 50,
    blade_length: 37.5,
    blade_width: 7,
    sword_weight: 7,
    point_of_balance: 6,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Skull King Longsword",
    image: "/assets/products/long_sword/Skull-King-Longsword.png",
    price: 349.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.LONGSWORD,
    description: [
      "In the world of fantasy, it is best to beware the wielder of the Skull King Long Sword. After all, the skulls on the hilt might symbolize a warriors prowess in dealing death to his enemies, and they also make the sword look really cool. This impressive sword features a stainless steel blade and a silver tone, cast metal hilt with a sharply curved guard that curls in towards the blade, depicting the great horns of a goat head. A serpent wraps around the grip, and a regal skull capped with a crown forms the pommel. The blade is unadorned, but it does feature a ricasso near the guard before its profile tapers into an edge. The blade has little distal taper, although the tip does narrow into a fine point, making this look like a weapon capable of delivering hefty cuts and hardy thrusts. Included with the decorative sword is a black leather sheath, which is perfect for storing the sword when it is not in use. For the death knight or blackguard, this Skull King Long Sword is an impressive weapon, one that is sure to send your foes running in fear, should they ever see you draw your sword.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1095,
    total_length: 41,
    blade_length: 33.5,
    blade_width: 1.5,
    sword_weight: 4,
    point_of_balance: 4,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "William Basic Longsword",
    image: "/assets/products/long_sword/William-Basic-Longsword.png",
    price: 222.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.LONGSWORD,
    description: [
      "The long sword from our Basic Edition. For a small price you get a fully usable foam weapon from our workshop in Cologne.",
      "All our foam weapons from the Basic Edition are made from robust components. The grip is one piece and molded from a softer polyurethane material. The blade comes from our proven 'Classic' Line and is firmly connected to the handle element to form the finished sword. The foam weapons of the Basic Edition mean safe fun in larp combat at a very low cost.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1075,
    total_length: 45,
    blade_length: 32,
    blade_width: 4,
    sword_weight: 3,
    point_of_balance: 4,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Hilt Rapier",
    image: "/assets/products/rapier/Black-Hilt-Rapier.png",
    price: 339.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.RAPIER,
    description: [
      "Not all rapiers were fine weapons, made for the social elite of the renaissance. They were a common sword of the day, and so some, like this Black Hilt Rapier, were made to be less ornate. Being less fancy does little to decrease this blades effectiveness. This rapier is straight-forward in its design, possessing a look suitable for any swordsman who prefers a thrusting style of sword. The blade is crafted from stainless steel, and its thin, needle-like shape makes it look perfect for deadly thrusts and defensive parries. The cast-metal guard features a cage around the swords ricasso, long quillons for defense, and a downward swept shell around the grip. The grip is black and swelled slightly so that it fits nicely into the hand. A round scent-stopper pommel finishes the blade. Included with the sword is a black scabbard for safely securing the blade when it is not in use or display. At your side, this Black Hilt Rapier makes for a great side-arm to complete your ideal renaissance or musketeer look, and on your wall, it will serve well as a fine display piece to remind others of a time when honor was won at the point of a sword.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1095,
    total_length: 43,
    blade_length: 37,
    blade_width: 4,
    sword_weight: 4,
    point_of_balance: 3,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Christus Imperat Rapier",
    image: "/assets/products/rapier/Christus-Imperat-Rapier.png",
    price: 99.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.RAPIER,
    description: [
      "This rapier is heavily inspired by an original kept within the Royal Armouries. It has a blade of well-tempered high carbon steel. Christus Imperat (Christ Commands) is etched into the fuller on both sides. The complex and vibrantly spiralled guard of this rapier is made of metal with an antiqued steel finish.",
      "The pommel is likewise crafted in metal with an antiqued finish and the grip is elaborately wrapped in steel wire and surmounted by turks heads knots of twisted steel braid. The scabbard is of black leather and its chape and throat fittings are of metal with an antiqued steel finish.",
      "The rapier is commonly portrayed as a lightning fast sword and while it is certainly not a heavy or remotely cumbersome weapon, the notion that it is used in dizzyingly fast and deft flourishes is an exaggeration. Such techniques are directly inspired instead by the shorter smallsword and sport fencing. Due to its relatively similar form these properties have been assumed upon the rapier in many movies and video games.",
      "Historically the rapier is used not as a wildly moving blade with elaborate flourishes and manic blade-to-blade clashing with the foe – it is instead a calculated thrusting weapon. Its long blade length keeps the foe at bay and when an opening through his defense appears a swordsman with a rapier can strike at a significant distance with his sword held outwards matched with a forward step. The thin blade easily pierces an unarmored opponent and a mere few inches of penetration to the torso are likely to cause a serious wound, or a great amount of internal bleeding at the least.",
    ],
    metal_type: MetalType.SPRING_STEEL,
    total_length: 48,
    blade_length: 38.25,
    blade_width: 4,
    sword_weight: 3,
    point_of_balance: 3,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Final Fantasy Rapier",
    image: "/assets/products/rapier/Final-Fantasy-Rapier.webp",
    price: 388.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.RAPIER,
    description: [
      "Genesis Rhapsodos wields a crimson broadsword with a rapier-style hilt, named the Rapier. Genesis is able to infuse his sword with magic, similar to the Spellblade. When transformed into Genesis Avatar, Genesis wields a much larger version of this sword. G Shadow Knights, a powerful type of Genesis Copy spawned by Genesis Avatar, wield a version of Genesis's rapier with a bright violet blade.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1095,
    total_length: 37,
    blade_length: 28,
    blade_width: 3,
    sword_weight: 2,
    point_of_balance: 3.5,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Practical Rapier",
    image: "/assets/products/rapier/Practical-Rapier.png",
    price: 45.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.RAPIER,
    description: [
      "The Practical Rapier has an SCA-approved 43 inch Schlager blade. The tapered blade form provides superior balance compared to the traditional parallel-sided schlagers of the same length, making for a faster sword. The high-carbon steel blade provides good flexibility and is button-tipped for safety. The hilt features solid steel construction with a wire wrapped grip. No scabbard available.",
    ],
    metal_type: MetalType.SPRING_STEEL,
    total_length: 49.25,
    blade_length: 43,
    blade_width: 4,
    sword_weight: 3,
    point_of_balance: 3.5,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Swept Hilt Rapier",
    image: "/assets/products/rapier/Swept-Hilt-Rapier.png",
    price: 382.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.RAPIER,
    description: [
      "Precision, agility, and technique are all three things that the rapier emphasizes, thanks to its narrow thrusting blade. This Black Wire Hilt Rapier recreates the look of a historic sword that gradually changed the way men fought with blades. Perhaps the most iconic feature of the rapier was the fantastic hilt designs, which provided both an aesthetic quality and a functional defense to any rapiers look. In this particular model, the ornately swept hilt forms a cage of quillons that keeps the main hand fairly safe when it grips the hilt, both in a traditional and a finger-forward grip. The quillons are solid black and constructed from steel, while the blade of the rapier is crafted from mirror-polished stainless steel and left unsharpened. The hilt features a scent-stopper shaped pommel, again done in black, as well as a rubber ABS handle that is wrapped with silver wire, to provide the right combination of grip and look. Included with the rapier is a wood scabbard with black steel fittings at the throat and chape. Classically styled, this Black Wire Hilt Rapier is the perfect sword to take in hand when you want a realistic looking blade that will serve you well in your endeavors, both for fun swinging and for delightful costume use and display.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1095,
    total_length: 43.5,
    blade_length: 35,
    blade_width: 3,
    sword_weight: 5,
    point_of_balance: 4,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Woingear Rapier",
    image: "/assets/products/rapier/Woingear-Rapier.png",
    price: 532.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.RAPIER,
    description: [
      "The rapier is the classic dueling sword, fast and accurate. Thin and long, often with elaborate hilts and hand-guards, rapiers are designed for thrusting.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1045,
    total_length: 38,
    blade_length: 30,
    blade_width: 3,
    sword_weight: 5,
    point_of_balance: 4,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Engraved Dragon Wakizashi",
    image: "/assets/products/wakizashi/Black-Engraved-Dragon-Wakizashi.png",
    price: 489.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.WAKIZASHI,
    description: [
      "The typical image of a bokken is a full-sized wooden sword. However, training is not limited to a full-sized sword, and so bokken also come in all shapes and sizes. Our Black Engraved Dragon Wakizashi is an excellent example of this fact. And while this bokken is more ornamental then for actual training, the concept remains the same. Taking the size and shape of a wakizashi, also known as the companion sword, this bokken, if used in training, would be an accompaniment to the katana. Either as an off-handed blade or alone, as a last defense when the katana is far too large to be used properly. This wakizashi-bokken is made from a single piece of hard wood and stylishly finished with a black varnish. Engraved into the varnish is a Japanese-styled dragon, elegantly colored in natural wood-tones. The grip is wrapped in a fashion similar to wakizashi. For those who are looking to own a complete, ornamental bokken daisho set, this Black Engraved Dragon Wakizashi is an excellent and stylish beginning to the two-piece sword-set.",
    ],
    metal_type: MetalType.SPRING_STEEL,
    total_length: 30,
    blade_length: 21,
    blade_width: 2,
    sword_weight: 2,
    point_of_balance: 3,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Golden Blade Wakizashi",
    image: "/assets/products/wakizashi/Golden-Blade-Wakizashi.png",
    price: 976.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.WAKIZASHI,
    description: [
      "Looking for a sword that has a sense of luxury and danger? The Golden Blade Samurai Wakizashi may fit your needs and your excellent sense of style. Made from 1045 carbon steel, this sword has a gold-plated blade. The blade has the traditional curved shape found on many Japanese swords. The blade enters the handle at a black tsuba. Golden accents adorn the tsuba in addition to a cutout battle scene. Next, the sword features a black, wrapped handle with additional gold-colored accents. Finally, the sword comes with a black scabbard called a saya, a sword bag, and a certificate of authenticity. It easily matches the Golden Blade Samurai Katana (NP-F-586-GD), sold separately. Add this wakizashi to any sword collection or home decor for an eye-catching flair.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1075,
    total_length: 32,
    blade_length: 2,
    blade_width: 4,
    sword_weight: 3,
    point_of_balance: 3,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Koi Wakizashi",
    image: "/assets/products/wakizashi/Koi-Wakizashi.png",
    price: 573.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.WAKIZASHI,
    description: [
      "This Samurai sword is mounted in black and white and features black same (ray skin). The tsuka-ito is made of premium white Japanese cotton. A finely rendered koi with true front-and-back detail forms the black iron tsuba. The fittings are superbly antiqued, adding to the aesthetics of the piece. The saya features a deep black lacquer finish with a black and white striped cotton sageo. The Koi Wakizashi is supplied with a protective cloth bag and a traditional maintenance kit.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1060,
    total_length: 35,
    blade_length: 27.5,
    blade_width: 3,
    sword_weight: 2,
    point_of_balance: 2,
    sword_edge: SwordEdge.SHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Kondoru Wakizashi",
    image: "/assets/products/wakizashi/Kondoru-Wakizashi.png",
    price: 132.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.WAKIZASHI,
    description: [
      "This robust Wakizashi has a blade crafted from 1075 high carbon steel; the hilt is a highly durable full-tang construction created by riveting two halves of well-carved walnut to the thick blade tang. The practical tsuba is solid and tough iron and the habaki is brass.",
      "Included with the Wakizashi is a matching scabbard of polished walnut with iron fittings and a paracord wrap.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1060,
    total_length: 22.5,
    blade_length: 16.75,
    blade_width: 2.5,
    sword_weight: 2,
    point_of_balance: 3.5,
    sword_edge: SwordEdge.UNSHARPENED,
    engraving: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Pine Crane Wakizashi",
    image: "/assets/products/wakizashi/Pine-Crane-Wakizashi.png",
    price: 473.99,
    reviews: { ids: [], value: 0 },
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: SwordType.WAKIZASHI,
    description: [
      "The Pine Crane Wakizashi melds two strong symbols of Japanese culture for honor, loyalty, authority, divine protection and long-lived wisdom into a single sword. It makes a fine blade on its own or as a completed daisho set with the Pine Crane Katana.",
      "The blade is forged from T10 high carbon steel and was differentially tempered in the traditional manner to produce a hardened edge, visibly seen along a flowing hamon. The habaki and seppa mountings are silvered and the tsuba, fuchi and kashira hilt fittings are vibrantly detailed bronzed fittings – the top of the Crane’s head is detailed in brass on the tsuba. The wooden tsuka grip is bound in knotted black tsuka-ito cord; the grip panels are genuine rayskin and a pair of silvered crane menuki are fitted beneath the folds of the wrap.",
      "The saya scabbard is wood with a dark brown textured lacquer coating paired with a striped black finish at its throat. A copper flecked sageo cord in a charcoal hue finishes the scabbard. A cloth sword bag is included. There is a thumbnail link on this page to the matching Pine Crane Katana.",
      "Regal and endowed with the wisdom of a millennia are both the Crane and Pine in Japan and thus they have both been artfully melded into the symbology of this Katana. The Red Crown Crane holds a magnanimous perch in Japanese culture. Traditionally believed to live a thousand years the Crane stands well above the other birds in both stature and reverence and thus it is a symbol for wizened authority; One word from the Crane is a Japanese idiom for a final judgement on a matter that is not to be challenged. A strong symbol of honor and loyalty, the Crane mates for life.",
      "In Shinto the Pine Tree is often planted near the front gates to a shrine or temple, for it is believed that the Pines can invite the spirits of heavenly-descended gods to dwell within them. For this the Pines are thought be imbued with longevity, power and ancient wisdom.",
      "Crane and Pine stylistically entwined; this Katana give it deep roots to Japanese cultural symbolism for duty, honorable authority and heavenly wisdom. All matters of great spiritual import to the soul of the Samurai.",
    ],
    metal_type: MetalType.HIGH_CARBON_STEEL_1095,
    total_length: 28,
    blade_length: 20,
    blade_width: 1.5,
    sword_weight: 2,
    point_of_balance: 3,
    sword_edge: SwordEdge.SHARPENED,
    engraving: true,
  },
];

export default products;
