import { IProduct } from "../../mongoose/models/Product";
import mongoose from "mongoose";

const products: IProduct[] = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Acre Broadsword",
    image: "/assets/products/broadsword/Acre-Broadsword.png",
    price: 40.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Broadsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Final Fantasy Broadsword",
    image: "/assets/products/broadsword/Final-Fantasy-Broadsword.webp",
    price: 199.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Broadsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Imperial Knights Broadsword",
    image: "/assets/products/broadsword/Imperial-Knights-Broadsword.png",
    price: 399.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Broadsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Romanian Broadsword",
    image: "/assets/products/broadsword/Romanian-Broadsword.png",
    price: 399.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Broadsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Training Broadsword",
    image: "/assets/products/broadsword/Training-Broadsword.png",
    price: 499.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Broadsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Wooden Pirate Cutlass",
    image: "/assets/products/cutlass/Black-Wooden-Pirate-Cutlass.png",
    price: 50.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Cutlass",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Earth Cutlass",
    image: "/assets/products/cutlass/Earth-Cutlass.png",
    price: 109.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Cutlass",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Fantasy Cutlass",
    image: "/assets/products/cutlass/Fantasy-Cutlass.webp",
    price: 159.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Cutlass",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "LARP Corsair Cutlass",
    image: "/assets/products/cutlass/LARP-Corsair-Cutlass.png",
    price: 395.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Cutlass",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Samurai Sword Cutlass",
    image: "/assets/products/cutlass/Samurai-Swords-Cutlass.png",
    price: 599.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Cutlass",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Flower Katana",
    image: "/assets/products/katana/Black-Flower-Katana.png",
    price: 999.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Katana",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Katana",
    image: "/assets/products/katana/Black-Katana.png",
    price: 552.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Katana",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Final Fantasy Mako Katana",
    image: "/assets/products/katana/Final-Fantasy-Mako-Katana.webp",
    price: 385.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Katana",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Green Katana",
    image: "/assets/products/katana/Green-Katana.png",
    price: 1023.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Katana",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "LARP Dai Katana",
    image: "/assets/products/katana/LARP-Dai-Katana.png",
    price: 588.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Katana",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Random Katana",
    image: "/assets/product/katana/random-Katana.png",
    price: 329.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Katana",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Red Katana",
    image: "/assets/product/katana/Red-Katana.png",
    price: 884.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Katana",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Hunting Knife",
    image: "/assets/product/knifes/Hunting-Knife.png",
    price: 583.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Knife",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Huntn Fisch Fixed Blade Knife",
    image: "/assets/product/knifes/Huntn-Fisch-Fixed-Blade-Knife.webp",
    price: 329.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Knife",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Outdoor Edge Wild Knife",
    image: "/assets/product/knife/Outdoor-Edge-Wild-Knife.webp",
    price: 853.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Knife",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Pocket Knife Iowa Daryl's Gun Shop Knife",
    image: "/assets/product/knife/Pocket-Knife-Iowa-Daryl's-Gun-Shop-Knife.png",
    price: 103.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Knife",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Pocket Knife Le Thiers Knife",
    image: "/assets/product/knife/Pocket-Knife-Le-Thiers-Knife.jpg",
    price: 238.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Knife",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Medieval Longsword",
    image: "/assets/product/long_sword/Medieval-Longsword.png",
    price: 534.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Longsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Phantom Forces Longsword",
    image: "/assets/product/long_sword/Phantom-Forces-Longsword.webp",
    price: 384.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Longsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Robbert Stark Longsword",
    image: "/assets/product/long_sword/Robbert-Stark-Longsword.png",
    price: 853.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Longsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Skull King Longsword",
    image: "/assets/product/long_sword/Skull-King-Longsword.png",
    price: 349.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Longsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "William Basic Longsword",
    image: "/assets/product/long_sword/William-Basic-Longsword.png",
    price: 222.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Longsword",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Hilt Rapier",
    image: "/assets/product/rapier/Black-Hilt-Rapier.png",
    price: 339.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Rapier",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Christus Imperat Rapier",
    image: "/assets/product/rapier/Christus-Imperat-Rapier.png",
    price: 99.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Rapier",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Final Fantasy Rapier",
    image: "/assets/product/rapier/Final-Fantasy-Rapier.webp",
    price: 388.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Rapier",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Practical Rapier",
    image: "/assets/product/rapier/Practical-Rapier.png",
    price: 45.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Rapier",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Swept Hilt Rapier",
    image: "/assets/product/rapier/Swept-Hilt-Rapier.png",
    price: 382.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Rapier",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Woingear Rapier",
    image: "/assets/product/rapier/Woingear-Rapier.png",
    price: 532.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Rapier",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Black Engraved Dragon Wakizashi",
    image: "/assets/product/wakizashi/Black-Engraved-Dragon-Wakizashi.png",
    price: 489.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Wakizashi",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Golden Blade Wakizashi",
    image: "/assets/product/wakizashi/Golden-Blade-Wakizashi.png",
    price: 976.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Wakizashi",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Koi Wakizashi",
    image: "/assets/product/wakizashi/Koi-Wakizashi.png",
    price: 573.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Wakizashi",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Kondoru Wakizashi",
    image: "/assets/product/wakizashi/Kondoru-Wakizashi.png",
    price: 132.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Wakizashi",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Pine Crane Wakizashi",
    image: "/assets/product/wakizashi/Pine-Crane-Wakizashi.png",
    price: 473.99,
    reviews: [],
    is_in_stock: true,
    discount: 0,
    refurbished: false,
    type_sword: "Wakizashi",
  },
];

export default products;
